### ISSUE TITLE
These modifications are great! Have you asked for their inclusion in main Ethernet library?

### ISSUE THREAD

**Issue by q2dg** [per1234/EthernetMod#3]
It would be really good if this functionality could be merged, I think...
Thanks!

**Comment by per1234** [comment]
The automatic chipset selection in the W5x00 branch was taken from https://github.com/arduino/Arduino/pull/2325. It sounded like the Arduino developers were interested in the proposal but it hasn't gone anywhere since. The disadvantage is it does have some overhead. I see frequent posts on the forum from people trying to use W5500 with the Ethernet library so having the automatic chipset detection would make the Ethernet library much more user friendly. As you've pointed out recently, Arduino doesn't sell any W5100 based products so there's no reason that the Ethernet library needs to be limited to supporting only that chip. I'm currently transitioning from W5100 to W5500 in all my projects so it's really handy to allow the same code to run on either without me needing to make any changes to the sketch or library.

The `remoteIP()`, `remotePort()`, `localPort()` functions were taken from another PR: https://github.com/arduino/Arduino/pull/1700. They were rejected, unfortunately the link to the associated discussion with the reasoning for that rejection has gone dead and the Wayback Machine doesn't have it either. I didn't understand it because EthernetUDP has `remoteIP()` so it only seems consistent for Ethernet to have it also. I only use `remoteIP()` in my code but I find it very useful, I added the other functions because maybe they would be useful to someone else. According to SurferTim on the Arduino forum, there was a relatively recent change to the official Ethernet library that allows this stuff to be done from the sketch but I haven't had a chance to check it out and now I can't find where I saved the link to that thread. There's another option that allows you to use remoteIP() with the official Ethernet library: https://github.com/Chris--A/EthernetClientEx.

So that leaves `setClientTimeout()`. I'm not sure how useful this actually is. I think it's nice to be able to set this value. The stock Ethernet library has the timeout hard coded at 1000ms which is not very helpful if you have a watchdog timeout set to a shorter value.

I use this library in multiple of my projects without issues but it has gotten a bit behind the official Ethernet library. I need to spend some time pulling in some of the recent commits from that library.

**Comment by q2dg** [comment]
Thanks a lot for your so clear and long explanation!!

I've written a comment on official Ethernet library's github (https://github.com/arduino-libraries/Ethernet/issues/36#issuecomment-238085099) summarizing what you say here...but, frankly, looking at history I've no hope in future...

I'll close this issue, then, if you don't mind

**Comment by per1234** [comment]
Thanks! I'm glad you find this library useful. I definitely plan to update it a bit in the near future.
