### ISSUE TITLE
unplugged network cable causes unusable SD card

### ISSUE THREAD

**Issue by songrijie** [per1234/EthernetMod#4]
Thanks for the library. It helps a lot. 

I found a problem recently, on uno+w5100 shield.  When I include this library in sketch,  SD card is failing after network cable is unplugged.  It comes back if cable is plugged again. 

I tried to narrow down the issue.  It looks the cause is this lib.  After I simply removed this library from sketchbook, the issue disappeared.  

If you need the code, I will send you. 

Thanks,
Roger Song

**Comment by per1234** [comment]
I haven't been doing any work on this repository because supposedly there is an official Ethernet library in the works that will provide most of the features and is also higher quality:
https://github.com/PaulStoffregen/Ethernet

Last I heard it still was not considered fully finished for AVR but I think it's getting close at least. I haven't had a chance to thoroughly test it out.

So your code would be welcome but I can't guarantee I'll actually merge it into this repository. However, having it available in this repository for anyone who might find it useful it a good thing.

You might also take a look at PaulStoffregen/Ethernet to see if you can make an improvement to that library, which will likely be used by the entire Arduino community in the near future.

**Comment by songrijie** [comment]
Thanks for your quick response. 

The reason I use this repository is that I want to reduce the timeout value of client.connect(). 

Sorry for the confuse, that the "code", I mean the sketch.  This problem can be reproduced at will from my side. 

Anyway,  I will check the repository you referred to. Thanks!

Roger Song

**Comment by per1234** [comment]
Ah, yes. I suspected there might be something I needed from this library. PaulStoffregen/Ethernet does have automatic support for W5100/W5200/W5500 and I believe there are other ways to get the remote IP by just adding some code to the sketch or using a wrapper library. PaulStoffregen/Ethernet does have a bit more complex code in the connect function's while loop than the standard Arduino Ethernet library so I'd need to dig deeper to see what provisions there are for timing out. I like to have control over how long these functions can block. I use a watchdog timer but I'd rather for `EthernetClient.connect()` to fail before the watchdog resets the microcontroller. Before I added that function I had identified `EthernetClient.connect()` as the cause of some occasional resets in my system. `EthernetCliend.stop()` does still have the hardcoded 1000 ms timeout in PaulStoffregen/Ethernet, just like the official Ethernet library.

>After I simply removed this library from sketchbook, the issue disappeared.

I interpret that statement as saying that the official Ethernet library does not cause the problem but this one does. Is that correct?

What is the version of the Ethernet library you're using when the problem does not occur?

Which branch of this library are you using (Arduino-IDE-1.0.x, Arduino-IDE-1.5plus, or W5x00)?

**Comment by songrijie** [comment]
No, this problem doesn't  occur with standard Ethernet library.   I also tried PaulStoffregen/Ethernet, not problem. 

Here is my env:
Arduino-IDE-1.8.5,  with Ethernet-1.1.2, SD-1.2.2.  

Thanks!

**Comment by songrijie** [comment]
My sketch is used for something like access control.  The latest privilege is get from HTTP service, and saved in local SD card. If the HTTP response takes too long, say 300ms, I'd rather use stale privilege in local disk.  That's the purpose.

**Comment by per1234** [comment]
You forgot to answer one of my questions:
>Which branch of this library are you using (Arduino-IDE-1.0.x, Arduino-IDE-1.5plus, or W5x00)?

There are three different versions of the library in this repository. The default branch is Arduino-IDE-1.5plus, which was simply a few modifications of a previous version of the standard Ethernet library. The Arduino-IDE-1.0.x branch is compatible with Arduino IDE 1.0.x. The W5x00 branch has automatic support for W5200 and W5500 as well as W5100.

**Comment by songrijie** [comment]
Sorry, I use default Arduino-IDE-1.5plus.

**Comment by per1234** [comment]
Which version of this library were you using?

**Comment by songrijie** [comment]
latest 1.1.1

**Comment by per1234** [comment]
Please do this:

1. Sketch > Include Library > Manage libraries
2. Wait for download to finish
3. In the "Filter your search..." box, type "ethernet"
4. Click on "**Ethernet** Built-in by **Various**"
5. From the "Select Version" dropdown menu, select 1.1.1.
6. Click "Install"
7. Wait for installation to finish
8. Click "Close"
9. Test to see if the problem occurs with version 1.1.1 of the official Ethernet library.
10. If the problem does not occur, repeat the above process, stepping back one version number each time, until you find the newest version of the official Ethernet library where the problem does occur.

This information will determine whether there is a specific change made in the official Ethernet library since the last time I synced this library that is the solution for your issue.

**Comment by songrijie** [comment]
Really appreciate your help!

It turns out this problem does not occur on any of standard library. 

1.1.2  working
1.1.1  working
1.1.0  working
1.0.5  working
1.0.4  working
1.0.3  working
1.0.2  working
1.0.1  working
1.0.0  working

I also found... with this lib, after I unplugged cable, the consequential boot also failed with SD.begin() even I plugged it again .  One more boot makes it work.

**Comment by per1234** [comment]
OK, that makes it pretty clear it's something I broke rather than a fix I hadn't merged from the official library. The strange thing is that I really didn't make many changes in the Arduino-IDE-1.5plus branch. Please post a sketch that has the error with my library but not with the official library and I'll see what I can do.

**Comment by songrijie** [comment]
Thanks, I will try to make a simple sketch to reproduce this problem, and get back to you.

**Comment by songrijie** [comment]
Since this project involves other module like card reader, I managed to remove the redundant code.  After running into a few other problems,  this sketch reproduces this issue. 

### How this sketch works:
* Obtain IP address from DCHP
* [repeat with 1000ms interval] Make http get request, wait for 1st char returned;  check existing file in SD card with SD.exists(). 

You may please unplug network cable, and check the output in serial port. 

Sketch:
```
#include <SPI.h>
#include <SD.h>
#include <Ethernet.h> 

#define PIN_SD   4
//#define DEBUG

// existing filename under SD fs. 
const char fileName[] = "SERVER";

const char url[] = "/?sn=123456789&uid=12345";

IPAddress serverIP(103, 229, 212, 72);
EthernetClient client;

void setup() {

    Serial.begin(9600);
    Serial.print(F("Open SD ... "));

    if (!SD.begin(PIN_SD)) {
        Serial.println(F("SD failed!"));
        return;
    }

    Serial.println(F("SD done."));


    byte mac[6] = { 0xEF, 0x45, 0x54, 0x00, 0x35, 0xD3 };

    if ( Ethernet.begin(mac) == 0 ) {
        Serial.println( F("DHCP Failed!"));
        return;
    }
    else
        Serial.println( F("DHCP Works!") );

    printIPAddress();

    // This problem reproduces no matter 
    // timeout is set or not. 
    //client.setClientTimeout(500);


}

void loop() {

    Ethernet.maintain();

    // send HTTP GET, and wait for the 
    // 1st char returned. 
    Serial.println(getHttp(url));

    // I tried to introduce a small sleep
    // It doesn't help. 
    delay(100);

    // fix file list rewinding issue
    SD.exists("1");

    // This file is supposed to exist. 
    if ( SD.exists(fileName) )
        Serial.println("file found!");
    else
        Serial.println("file missing!");
  delay(1000);

}

void printIPAddress()
{
  Serial.print(F("IP: "));
  for (byte thisByte = 0; thisByte < 4; thisByte++) {
    // print the value of each byte of the IP address:
    Serial.print(Ethernet.localIP()[thisByte], DEC);
    Serial.print(".");
  }
  Serial.println();
}

/*
 * Genereic funtion to get HTTP
 * output. return the 1st char.
 */
char getHttp(char *str) {

    // Serial.println(F("getHttp"));
    // Serial.print(freeRam());
    char c = 0;

    if ( client.connect(serverIP, 80) ) {
        Serial.println(F("Connected!"));

        client.print(F("GET "));
        client.println(str);
        client.println();

        // Wait for response
        // Up to 254 * 2 = 512 ms
        for(char i = 0; i < 254; i++) {
            if (client.available()) {
            c=client.read();
            client.stop();
            return c;
            }
        delay(2);
        }
# ifdef DEBUG
    Serial.println(F("nothing get"));
# endif    
    client.stop();
    return '*';
    }
    else {
# ifdef DEBUG
    Serial.println(F("not connected"));
# endif
    // if connect() return false, 
    // close the connection and return
    // '*'
        if (client.connected() ) {
            client.stop();
        }
        return '*';
    }
}
```

### With official library:

```
Open SD ... SD done.
DHCP Works!
IP: 192.168.31.224.
Connected!
-
file found!
Connected!
-
file found!
Connected!
-
file found!
Connected!
-
file found!  <---- unplug cable
*
file found!
*
file found!
*
file found!
*
file found!

```

### With lib in this repo

Serial output:
```
Open SD ... SD done.
DHCP Works!
IP: 192.168.31.224.
Connected!
-
file found!
Connected!
-
file found!
Connected!
-
file found!
Connected!
-
file found!
Connected!
-
file found! <----- unplug cable
*
file missing!
*
file missing!
*
file missing!
*
file missing!
```

**Comment by per1234** [comment]
Thanks. That's very helpful. I'll look into this as soon as I get a chance.

**Comment by songrijie** [comment]
I can reproduce this problem with nano+w5100 even with the official lib. 

It seems the problem is from ICSP slave conflict.  When putting `SD.begin(PIN_SD)` ahead of SD calls, the problem resolved. 

It looks like when ethernet is activated, we'd better enable SD before calling it. This could be caused by SD lib or ethernet lib. One of them doesn't handle it well.   

 Not sure this is issue or not. Thank you so much anyway!

**Comment by per1234** [comment]
I have a Seeed Studios W5200 Ethernet Shield v2 with SD card and with that shield I've found that I need to set the SD CS pin HIGH before calling `Ethernet.begin()`, otherwise it fails. This is done in the example sketches that are included with their official W5200 EthernetV2.0 library. This isn't necessary with the other Ethernet/SD shields I own and the Ethernet and Ethernet2 libraries don't have any manipulation of the SD CS pin. My understanding is that the best hardware design practices are to add a pullup resistor to the CS lines so that the SPI devices will default to being disabled unless they are specifically enabled by setting the CS pin LOW. My suspicion is that Seeed did not add this pullup and that's why it's necessary to set the pin HIGH in the sketch. I wonder if there is something similar with your SD?

**Comment by songrijie** [comment]
It's most likely caused by hardware design... Since we can workaround the issue, I'm glad to close this issue.  Really appreciate your help.
